services:
  - type: web
    name: yt-nexus
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT -k gevent app:app
    maxDuration: 120
    maxInstance: 1
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11"
